export const FETCH_VLOGS_REQUEST = 'FETCH_VLOGS_REQUEST';
export const FETCH_VLOGS_SUCCESS = 'FETCH_VLOGS_SUCCESS';
export const FETCH_VLOGS_FAILURE = 'FETCH_VLOGS_FAILURE';
export const REMOVE_FIELD_ERROR = 'REMOVE_FIELD_ERROR';
