export const FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE';
export const VIEW_BLOG_REQUEST = 'VIEW_BLOG_REQUEST';
export const VIEW_BLOG_SUCCESS = 'VIEW_BLOG_SUCCESS';
export const VIEW_BLOG_FAILURE = 'VIEW_BLOG_FAILURE';
export const REMOVE_FIELD_ERROR = 'REMOVE_FIELD_ERROR';
