export const FETCH_TALENTS_REQUEST = 'FETCH_TALENTS_REQUEST';
export const FETCH_TALENTS_SUCCESS = 'FETCH_TALENTS_SUCCESS';
export const FETCH_TALENTS_FAILURE = 'FETCH_TALENTS_FAILURE';
export const VIEW_TALENT_REQUEST = 'VIEW_TALENT_REQUEST';
export const VIEW_TALENT_SUCCESS = 'VIEW_TALENT_SUCCESS';
export const VIEW_TALENT_FAILURE = 'VIEW_TALENT_FAILURE';
export const REMOVE_FIELD_ERROR = 'REMOVE_FIELD_ERROR';
